image: $DOCKER_REGISTRE_URL/$DOCKER_REGISTRE_NAMESPACE_INT/node-build:14-alpine

# workflow stages are imported from templates
include:
  - project: 'build/gitlab/gitlab-ci'
    file: '/templates/base.yml'
  - project: 'build/gitlab/gitlab-ci'
    file: '/templates/release-module.yml'

stages:
  - test
  # - sonar
  - dist
  - artifact
  - release
  - deploy

# lint:
#   stage: test
#   rules:
#     - if: $CI_COMMIT_TAG == null
#   before_script:
#     - npm ci
#   script:
#     - npm run lint

audit:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - gitlabci-npm-audit break-build
    - gitlabci-npm-audit-compare

outdated:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  before_script:
    - npm ci
  script:
    # Check the npm outdated output
    # break-build not yet
    - gitlabci-npm-outdated

test:
  stage: test
  rules:
    # except tags
    - if: $CI_COMMIT_TAG == null
  script:
    - npm ci
    - npm test

# sonar:
#   stage: sonar
#   script:
#     - /scripts/quality-gate-sonar.sh A
#     - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_KEY -Dsonar.projectKey=$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG -Dsonar.projectName=$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
#     - gitlabci-sonar-compare report
#   dependencies:
#     - test
#   rules:
#     - if: $CI_COMMIT_TAG == null

dist:
  stage: dist
  rules:
    - when: always
  before_script:
    # bump version with feature branch name
    - export version=`cat package.json | jq -r '.version'`
    - if [ -z $CI_COMMIT_TAG ]; then version=$version-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID && npm version --no-git-tag-version $version; fi;
    - npm ci
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - package.json
      - dist
      - loader

artifact:
  stage: artifact
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - npm publish
  needs:
    - dist

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'init'
  before_script:
    - npm ci
    - apk add sshpass
  script:
    - npm run build-storybook -s www/build
    - cd storybook-static/
    - export SSHPASS=$SSH_PASS_OUTILS
    - sshpass -e scp -o stricthostkeychecking=no -r . $USER@$SERVER:/usr/share/nginx/html/ux-ui/design-system/
  tags:
    - internal
