image: $DOCKER_REGISTRE_URL/$DOCKER_REGISTRE_NAMESPACE_INT/node-build:14-alpine

# workflow stages are imported from templates
include:
  - project: 'build/gitlab/gitlab-ci'
    file: '/templates/base.yml'

stages:
  - test
  # - sonar
  - release

# lint:
#   stage: test
#   rules:
#     - if: $CI_COMMIT_TAG == null
#   before_script:
#     - npm ci
#   script:
#     - npm run lint

audit:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - gitlabci-npm-audit break-build
    - gitlabci-npm-audit-compare

outdated:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  before_script:
    - npm ci
  script:
    # Check the npm outdated output
    # break-build not yet
    - gitlabci-npm-outdated

test:
  stage: test
  rules:
  # except tags
    - if: $CI_COMMIT_TAG == null
  script:
   - npm ci
   - npm test

# sonar:
#   stage: sonar
#   script:
#     - /scripts/quality-gate-sonar.sh A
#     - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_KEY -Dsonar.projectKey=$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG -Dsonar.projectName=$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
#     - gitlabci-sonar-compare report
#   dependencies:
#     - test
#   rules:
#     - if: $CI_COMMIT_TAG == null

release:
  stage: release
  rules:
  # only tags
    - if: $CI_COMMIT_TAG
  script:
    - RELEASE_VERSION=`echo $CI_COMMIT_REF_NAME | cut -d "v" -f 2`
    - if [ "$(grep '\"version\":' package.json | cut -d\" -f4)" != $RELEASE_VERSION ]; then  echo Différence de version entre le tag git et le package.json; exit 1; fi;
    - npm ci
    - npm publish
