image: $DOCKER_REGISTRE_URL/$DOCKER_REGISTRE_NAMESPACE_INT/node-build:14-alpine

# workflow stages are imported from templates
include:
  - project: 'build/gitlab/gitlab-ci'
    file: '/templates/base.yml'
  - project: 'build/gitlab/gitlab-ci'
    file: '/templates/release-module.yml'

stages:
  - test
  # - sonar
  - dist
  - artifact
  - release
  - deploy

.install:
  before_script:
    - npm ci

lint:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  extends:
    - .install
  script:
    - npm run lint

audit:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - gitlabci-npm-audit break-build
    - gitlabci-npm-audit-compare

outdated:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  before_script:
    - npm ci
  script:
    # Check the npm outdated output
    # break-build not yet
    - gitlabci-npm-outdated

test:
  stage: test
  image: $DOCKER_REGISTRE_URL/$DOCKER_REGISTRE_NAMESPACE_INT/node-build:14-debian
  rules:
    # except tags
    - if: $CI_COMMIT_TAG == null
  extends:
    - .install
  script:
    - npm test

sonar:
  stage: sonar
  script:
    - /scripts/quality-gate-sonar.sh A
    - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_KEY -Dsonar.projectKey=$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG -Dsonar.projectName=$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    - gitlabci-sonar-compare report
  dependencies:
    - test
  rules:
    - if: $CI_COMMIT_TAG == null

dist:
  stage: dist
  rules:
    - when: always
  extends:
    - .install
  script:
    # bump version with feature branch name
    - export version=`cat package.json | jq -r '.version'`
    - if [ -z $CI_COMMIT_TAG ]; then version=$version-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID && npm version --no-git-tag-version $version; fi;
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - package.json
      - dist
      - loader

artifact:
  stage: artifact
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - npm publish
  needs:
    - dist

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'init'
  extends:
    - .install
  script:
    - npm run build-storybook
    - mv storybook-static public
  artifacts:
    paths:
      - public
