image: $DOCKER_REGISTRE_URL/$DOCKER_REGISTRE_NAMESPACE_INT/node:18-build

# workflow stages are imported from templates
include:
  - project: 'build/gitlab/gitlab-ci'
    file: '/templates/release-module.yml'

stages:
  - test
  - sonar
  - dist
  - artifact
  - review
  - chromatic-publish
  - release
  - bot-publish
  - deploy

.install:
  before_script:
    - corepack enable
    - pnpm i

lint:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  extends:
    - .install
  script:
    - pnpm turbo lint

audit:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - gitlabci-npm-audit break-build --PACKAGE_MANAGER pnpm
    - gitlabci-npm-audit-compare

# outdated:
#   stage: test
#   rules:
#     - if: $CI_COMMIT_TAG == null
#   extends:
#     - .install
#   script:
#     # Check the npm outdated output
#     # break-build not yet
#     - gitlabci-npm-outdated

test:
  stage: test
  rules:
    # except tags
    - if: $CI_COMMIT_TAG == null
  extends:
    - .install
  script:
    - pnpm turbo test
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - coverage
    reports:
      junit:
        - coverage/junit.xml

sonar:
  stage: sonar
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - gitlabci-quality-gate A+++
    - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_KEY -Dsonar.projectKey=$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG -Dsonar.projectName=$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    - gitlabci-sonar-compare report
  needs:
    - test

dist:
  stage: dist
  rules:
    - when: always
  extends:
    - .install
  script:
    # bump version with feature branch name
    - export version=`cat package.json | jq -r '.version'`
    - if [ -z $CI_COMMIT_TAG ]; then version=$version-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID && npm version --no-git-tag-version $version; fi;
    - pnpm turbo build
  artifacts:
    expire_in: 1 week
    paths:
      - package.json
      - dist
      - loader
      - www

chromatic-publish:
  stage: chromatic-publish
  rules:
    # only tags
    - if: $CI_COMMIT_TAG
  extends:
    - .install
  script:
    - npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --auto-accept-changes --branch-name master

artifact:
  stage: artifact
  rules:
    - if: $CI_COMMIT_TAG == null
  extends:
    - .install
  script:
    - npm publish
  needs:
    - dist

review_app:
  stage: review
  rules:
    - if: $CI_MERGE_REQUEST_ID
  extends:
    - .install
  script:
    - pnpm turbo storybook:build
    - mv storybook-static public
  needs:
    - dist
  artifacts:
    paths:
      - public
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: 'http://core.pages.mgdis.fr/-/core-ui/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html'
    on_stop: stop_review_app
    auto_stop_in: 1 week

stop_review_app:
  stage: review
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
  script:
    - echo "👋"
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop

bot-publish:
  stage: bot-publish
  rules:
    # only tags
    - if: $CI_COMMIT_TAG
  script:
    - cd tools/release-bot
    - npm ci
    - ./bin/release.js

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  extends:
    - .install
  script:
    - npm run storybook:build
    - mv storybook-static public
  needs:
    - dist
  artifacts:
    paths:
      - public
